version: '3'

volumes:
    z88dk_source: {}

services:
  z88dk:
    container_name: z88dk_build
    image: z88dk
    build:
      context: .
      dockerfile: z88dk.Dockerfile
    volumes:
      - .:/src
      - z88dk_source:/opt/z88dk
    command: ["/bin/sh"]
